//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aesir.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class TileManager : global::System.Configuration.ApplicationSettingsBase {
        
        private static TileManager defaultInstance = ((TileManager)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TileManager())));
        
        public static TileManager Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int ReleasePeriod {
            get {
                return ((int)(this["ReleasePeriod"]));
            }
            set {
                this["ReleasePeriod"] = value;
            }
        }
    }
}
